remote_theme: just-the-docs/just-the-docs
plugins:
- kramdown
- jekyll-remote-theme
title: Web Forms To Blazor
# For copy button on code
enable_copy_code_button: true
callouts:
  note-title:
    title: Note
    color: blue
